### ISSUE TITLE
404 - On Page Refresh Crash

### ISSUE THREAD

**Issue by JBNavadiya** [gdgcloudahmedabad/gdgcloudahmedabad.github.io#1]
@harshcrop 
To replicate the issue, follow the below steps:
1. Go to https://gdgahmedabad.cloud/events
2. Refresh the page

You will see 404 page.

![image](https://user-images.githubusercontent.com/2223354/68701549-09cafb00-05ad-11ea-89ad-928df6506796.png)

**Comment by harshcrop** [comment]
@JBNavadiya  thank you for point out this issue let me check what goes wrong here

**Comment by harshcrop** [comment]
@JBNavadiya I talk with Viraj and he told me that we need to deploy this website to firebase to avoid this error
