### ISSUE TITLE
Facebook Broken Links

### ISSUE THREAD

**Issue by JBNavadiya** [gdgcloudahmedabad/gdgcloudahmedabad.github.io#2]
@harshcrop, please update the fb links in footer.

![image](https://user-images.githubusercontent.com/2223354/68701882-b6a57800-05ad-11ea-8778-83b015f1cdf1.png)

**Comment by JBNavadiya** [comment]
@harshcrop also change the email id gdgcloudahmedabad@gmail.com to gcdcahmedabad@gmail.com

**Comment by harshcrop** [comment]
fix the issue
